# Generated by Django 4.0.4 on 2022-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
