# Generated by Django 4.0.4 on 2022-11-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='number_of_rounds',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
