# Generated by Django 4.0.4 on 2022-11-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bout_name', models.CharField(max_length=70)),
                ('fans_avrg_one', models.IntegerField()),
                ('ofc_score_one', models.IntegerField()),
                ('fans_avrg_two', models.IntegerField()),
                ('ofc_score_two', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('fighter_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Red', to='fighters.fighter')),
                ('fighter_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blue', to='fighters.fighter')),
            ],
        ),
    ]
