# Generated by Django 4.0.4 on 2023-01-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bout_name', models.CharField(max_length=70)),
                ('number_of_rounds', models.IntegerField()),
                ('red_judge_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blue_judge_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('results', models.CharField(max_length=70)),
                ('blue_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blue', to='fighters.fighter')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('red_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Red', to='fighters.fighter')),
            ],
        ),
    ]
