# Generated by Django 4.0.4 on 2022-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ofc_score_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ofc_score_two',
        ),
        migrations.AddField(
            model_name='match',
            name='judge_avg_one',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='judge_avg_two',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fans_avrg_one',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fans_avrg_two',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
