# Generated by Django 4.0.4 on 2022-11-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='event_id',
            new_name='event',
        ),
    ]
