# Generated by Django 4.0.4 on 2022-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_event_id_match_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='number_of_rounds',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
