# Generated by Django 4.0.4 on 2022-12-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_remove_match_fans_avrg_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='fighter_two',
            new_name='blue_corner',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='judge_avg_two',
            new_name='blue_judge_avg',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fighter_one',
            new_name='red_corner',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='judge_avg_one',
            new_name='red_judge_avg',
        ),
    ]
