# Generated by Django 4.0.4 on 2022-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fan_acm_points', models.IntegerField()),
                ('ofc_acm_points', models.IntegerField()),
            ],
        ),
    ]
