# Generated by Django 4.0.4 on 2022-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fan_acm_points',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='ofc_acm_points',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
