# Generated by Django 4.0.4 on 2022-11-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_alter_fighter_fan_acm_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='fan_acm_points',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='ofc_acm_points',
        ),
    ]
