# Generated by Django 4.0.4 on 2022-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_remove_fighter_fan_acm_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image_link',
            field=models.CharField(default='https://mitchrappfan.files.wordpress.com/2015/08/mystery-character-three.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
